title: Cameron and Jeremiah's Wedding
author: Jeremiah and Baker
email: hello@cameronandjeremiah.com
description: >-
  Join our celebration of love.
event_date: May 18, 2019
location: Blowing Rock, North Carolina

# Base
url :  "http://cameronandjeremiah.com"
baseurl: ""

# SEO Settings
title_separator: "―"
locale: "en"
og_image:
twitter:
  username: "@baarbeh"
facebook:
  publisher: 695210511
google_site_verification: "BmGoJ0f8yHRSCM0F2Snq-yrLgbv3oUxxWh_zdfLDHJA"
bing_site_verification:
keywords : # Seperate with comma 
brand : My Project

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-92975012-2"

# Services 
mapbox:
  accessToken: "pk.eyJ1Ijoib3BlbmFpciIsImEiOiJjaWxheGcxdzIwZGxydHlsenJpOXJ5azZxIn0.uZ-GuqO9YrQ6HIbMH6cX9w"

    # Build Settings
permalink: /:title/
markdown : kramdown
include :
- _pages
exclude :
  - node_modules
plugins: 