title: Cameron and Jeremiah's Wedding
author: Jeremiah and Baker
email: hello@cameronandjeremiah.com
description: >-
  Join our celebration of love.
event_date: May 18, 2019
location: Blowing Rock, North Carolina

# Base
url :  "https://cameronandjeremiah.github.io"
baseurl: ""


# SEO Settings
title_separator: "―"
locale: "en"
og_image:
twitter:
  username: "@baarbeh"
facebook:
  publisher: 695210511
google_site_verification: # Add verification code
bing_site_verification:
keywords : # Seperate with comma 
brand : My Project

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: ""

# Build Settings

markdown : kramdown
exclude :
  - node_modules
plugins: 